FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV API_BASE_URL=http://api:8000

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY src /app/src

EXPOSE 8501

CMD [
  "streamlit",
  "run",
  "src/streamlit_app.py",
  "--server.address=0.0.0.0",
  "--server.port=8501"
]
